import { Chat } from '@team-plain/react-chat-ui';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Plain NextJS Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Plain NextJS Example</h1>
      <div className="chat__wrapper">
        {/* 
          Add the Chat component anywhere on your site.
          Make sure it's wrapped in the PlainProvider
        */}
        <Chat />
      </div>
    </div>
  );
};

export default Home;
